name: example
description: Example for flutter_hashtag_picker
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hashtag_picker:
    path: ../
