name: flutter_hashtag_picker
description: >
  A customizable Flutter widget for picking hashtags, with four built-in styles (purple, green, blue outline, orange pill). 
  Easily integrate hashtag selection in your social, productivity, or content creation apps.

version: 0.0.1
homepage: https://github.com/BrillianceOsprey/flutter_hashtag_picker
repository: https://github.com/BrillianceOsprey/flutter_hashtag_picker
issue_tracker: https://github.com/BrillianceOsprey/flutter_hashtag_picker/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

license: MIT  # <-- Here, the MIT license is specified
